# Changes the 'app' container IP to the wrong IP [maint_app_ip],  so 'web'
# cannot connect to it. This makes 'web' respond quickly with a status 502,
# which is good when in maintenance mode where we want to show a
# "We're upgrading the server" message — instead of 'web' being able to connect
# to 'app'; then it won't respond to the end user until half a minute (?)
# has elapsed.

services:
  web:
    extra_hosts:
        # Try connecting to a non-existing IP on a subnet we *can* access.
        # Because if 'web' tries to connect to something outside the subnet, seems
        # it justs "hang", maybe the connection would eventually timeout?
        #
        # 'web' is on the fe_int_net subnet:  FE_INT_NET_SUBNET = 172.26.2.0/24
        # and the correct app IP is:          FE_INT_NET_APP_IP = 172.26.2.41
        # see ../.env.
        #
        app: 172.26.2.127  # intentionally wrong

