# Talkyard, discussion forum software, v1. Production installation on a single server.
#
# Dockerfiles for the Docker images are in another Git repo:
# https://github.com/debiki/talkyard, at: images/(service-name)/Dockerfile
#
# There's an image build script: https://github.com/debiki/talkyard/blob/main/Makefile,
# the `prod-images` and `tag-and-push-latest-images` targets.

# Docker Compose file spec:
# https://github.com/compose-spec/compose-spec/blob/main/spec.md


# You can override this in docker-compose.override.yml.
# Volume names get prefixed by the COMPOSE_PROJECT_NAME = 'talkyard-v1_', from .env.
volumes:
  web-generated:
  pub-files:
  priv-files:
  pg-data:
  redis-data:
  es-data:
  es-logs:

# See: https://docs.docker.com/compose/how-tos/use-secrets/
secrets:
  postgres_password:
    file: ./secrets/postgres_password.txt
  #backup_password:
  #  file: ./secrets/backup_password.txt


# Internal networks are isolated from the external world, can't access the Internet.
# See: https://docs.docker.com/reference/compose-file/networks/#internal
#
# The netw names get prefixed with the COMPOSE_PROJECT_NAME.
#
networks:
  # Frontend public network. Connects Nginx to the Internet.
  fe_pub_net:
    ipam:
      config:
        - subnet: ${FE_PUB_NET_SUBNET}
  # So Nginx can talk to the app server.
  fe_int_net:
    internal: true
    ipam:
      config:
        - subnet: ${FE_INT_NET_SUBNET}
  # Backend network: the app server and various databases.
  be_int_net:
    internal: true
    ipam:
      config:
        - subnet: ${BE_INT_NET_SUBNET}
  # So the app server can connect to the egress proxy.
  eg_int_net:
    internal: true
    ipam:
      config:
        - subnet: ${EG_INT_NET_SUBNET}
  # So the egress proxy can access the Internet, e.g. to send webhooks or fetch link previews.
  eg_pub_net:
    ipam:
      config:
        - subnet: ${EG_PUB_NET_SUBNET}

# See: https://github.com/compose-spec/compose-spec/blob/main/spec.md#logging
x-logging: &default_logging
  # This driver rotates logs, so won't run out of disk.
  driver: local


services:
  web:
    image: ${DOCKER_REG_ORG}/talkyard-web:${PINNED_VERSION_TAG:-${VERSION_TAG}}
    # dockerfile: https://github.com/debiki/talkyard/blob/main/images/web/Dockerfile
    restart: always
    volumes:
      # Nginx `server {...}` blocks for your Talkyard forum.
      - ./conf/web/sites-enabled:/etc/nginx/sites-enabled:ro
      # The LetsEncrypt ACME account key gets generated by run-envsubst-gen-keys.sh.
      # Once done, you could make this dir read-only: append ':ro' to the next line.
      - web-generated:/etc/nginx/generated
      # Don't, however, mount priv-files here.
      - pub-files:/var/talkyard/v1/pub-files:ro

      # Optionally, add a wildcard cert volume here:
      # talkyard-wildcard-certs:/etc/wildcard-certs:ro
      # Fetch certs in a Docker container using e.g. LEGO https://github.com/go-acme/lego
      # that mounts the same volume, run in a cron job,
      # and edit:  ./conf/web/sites-enabled/talkyard-servers.conf
      # add e.g.:  ssl_certificate /etc/wildcard-certs/...something.crt;
      #      and:  ssl_certificate_key ...

    ports:
      - '80:80'
      - '443:443'
    networks:
      fe_pub_net:
        ipv4_address: ${FE_PUB_NET_WEB_IP}
      fe_int_net:
        ipv4_address: ${FE_INT_NET_WEB_IP}
    depends_on:
      - app
      - cache
    logging: *default_logging
    environment:
      TY_NGX_ERROR_LOG_LEVEL: 'info'  # or 'notice' or 'debug'
      # TY_NGX_ACCESS_LOG_CONFIG: 'tyalogfmt'
      ## Max uploaded file size, e.g. uploaded images or backups to restore:
      # TY_NGX_LIMIT_REQ_BODY_SIZE: '25m'
      ## To let any CDN of yours bypass Ty's Nginx rate limits:
      # X_PULL_KEY: '...'
      # CDN_PULL_KEY: '...'

    security_opt:
      - no-new-privileges=true
    # When cap_drop is ALL, it gets processed before cap_add, see:
    # https://stackoverflow.com/a/63219871
    # and:
    # https://github.com/moby/moby/blob/1c39b1c44c973f18f39bd684c6aba57bb96510fe/oci/caps/utils.go#L120
    cap_drop:
      - ALL
    cap_add:
      # Without CHOWN:
      # nginx: [emerg] chown("/opt/nginx/proxy-cache", 100) failed (1: Operation not permitted)
      - CHOWN
      # To bypass file read, write, and execute permission checks:
      # (DAC means "discretionary access control", and DAC_OVERRIDE)
      # Without DAC_OVERRIDE:
      # nginx: [emerg] mkdir() "/var/cache/nginx/client_temp" failed (13: Permission denied)
      - DAC_OVERRIDE
      # To change the group and user id of a process: (so Nginx won't need to run as root)
      - SETGID
      - SETUID
      # To bind to lower ports. Maybe listen on 8080 instead, and map port 80:8080?
      - NET_BIND_SERVICE

  app:
    image: ${DOCKER_REG_ORG}/talkyard-app:${PINNED_VERSION_TAG:-${VERSION_TAG}}
    # dockerfile: https://github.com/debiki/talkyard/blob/main/images/app/Dockerfile.prod
    restart: always
    stdin_open: true  # otherwise Play Framework exits
    volumes:
      - ./conf/app/play-framework.conf:/opt/talkyard/app/conf/app-prod-override.conf:ro  # see [4WDKPU2] in github.com/debiki/talkyard
      - pub-files:/var/talkyard/v1/pub-files
      - priv-files:/var/talkyard/v1/priv-files
      # So backups can be downloaded via the admin web interface. But read-only,
      # so evil bugs cannot destroy all backups.
      # - /var/opt/backups/talkyard/v1/:/var/opt/backups/talkyard/v1/:ro
    secrets:
      - postgres_password
    networks:
      fe_int_net:
        ipv4_address: ${FE_INT_NET_APP_IP}
      be_int_net:
        ipv4_address: ${BE_INT_NET_APP_IP}
      eg_int_net:
        ipv4_address: ${EG_INT_NET_APP_IP}
    depends_on:
      # Start also if other services are unhealthy, so can show admin troubleshooting tips.
      - rendr
      - cache
      - rdb
      - search
    logging: *default_logging
    environment:
      - TALKYARD_SECURE
      # The app always looks here, not configurable. [postgres_pw_path]
      # POSTGRES_PASSWORD_FILE=/tmp/postgres_password
      - TALKYARD_HOSTNAME
      - BECOME_OWNER_EMAIL_ADDRESS
    security_opt:
      - no-new-privileges=true
    cap_drop:
      - ALL
    cap_add:
      - CHOWN   # to make secrets readable to 'appuser'
      - FOWNER  #
      - DAC_OVERRIDE
      - SETUID  # to switch to 'appuser'
      - SETGID  #              'appgroup'

  rendr:
    image: ${DOCKER_REG_ORG}/talkyard-rendr:${PINNED_VERSION_TAG:-${VERSION_TAG}}
    # dockerfile: https://github.com/debiki/talkyard/blob/main/images/rendr/Dockerfile
    networks:
      be_int_net:
        ipv4_address: ${BE_INT_NET_RENDR_IP}
    logging: *default_logging
    cap_drop:
      - ALL

  cache:
    image: ${DOCKER_REG_ORG}/talkyard-cache:${PINNED_VERSION_TAG:-${VERSION_TAG}}
    # dockerfile: https://github.com/debiki/talkyard/blob/main/images/cache/Dockerfile
    restart: always
    volumes:
      - redis-data:/data
    networks:
      be_int_net:
        ipv4_address: ${BE_INT_NET_CACHE_IP}
    logging: *default_logging
    sysctls:
      net.core.somaxconn: 511
    security_opt:
      - no-new-privileges=true
    cap_drop:
      - ALL
    cap_add: # [enough_caps]? See: https://github.com/docker-library/postgres/issues/649
      - CHOWN  # [redis_cap_chown]
      - SETGID
      - SETUID

  rdb:
    image: ${DOCKER_REG_ORG}/talkyard-rdb:${PINNED_VERSION_TAG:-${VERSION_TAG}}
    # dockerfile: https://github.com/debiki/talkyard/blob/main/images/rdb/Dockerfile
    restart: always
    secrets:
      - postgres_password
    volumes:
      - pg-data:/var/lib/postgresql
      - ./conf/rdb:/var/lib/postgresql/conf:ro
    networks:
      be_int_net:
        ipv4_address: ${BE_INT_NET_RDB_IP}
    logging: *default_logging
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    security_opt:
      - no-new-privileges=true
    cap_drop:
      - ALL
    cap_add: # [enough_caps]? See: https://github.com/docker-library/postgres/issues/649
      - CHOWN
      - DAC_READ_SEARCH
      - DAC_OVERRIDE  # to copy Postgres secret
      - FOWNER
      - SETGID
      - SETUID
      - SYS_NICE

  search:
    image: ${DOCKER_REG_ORG}/talkyard-search:${PINNED_VERSION_TAG:-${VERSION_TAG}}
    # dockerfile: https://github.com/debiki/talkyard/blob/main/images/search/Dockerfile
    restart: always
    volumes:
      - es-data:/usr/share/elasticsearch/data
      # Deprecation logs aren't written to stdout, but to files in this dir,
      # auto rotated, max 5G in total.
      # See: https://www.elastic.co/docs/deploy-manage/monitor/logging-configuration/elasticsearch-deprecation-logs
      - es-logs:/usr/share/elasticsearch/logs
    networks:
      be_int_net:
        ipv4_address: ${BE_INT_NET_SEARCH_IP}
    logging: *default_logging
    environment:
      bootstrap.memory_lock: 'true'
      ES_JAVA_OPTS: '-Xms512m -Xmx512m'
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    security_opt:
      - no-new-privileges=true
    cap_drop:
      - ALL
    cap_add:  # [enough_caps]?
      # SYS_CHROOT? See  https://github.com/nasa-jpl/ASSESS/blob/master/docker-compose.yml
      - SETGID
      - SETUID

  # Egress proxy.
  # Stops Server Side Request Forgery (SSRF).
  egressp:
    image: ${DOCKER_REG_ORG}/talkyard-egressp
    read_only: true
    networks:
      eg_int_net:
        ipv4_address: ${EG_INT_NET_EGRESSP_IP}
      eg_pub_net:
        ipv4_address: ${EG_PUB_NET_EGRESSP_IP}

  backup:
    image: ${DOCKER_REG_ORG}/talkyard-backup:${PINNED_VERSION_TAG:-${VERSION_TAG}}
    # dockerfile: https://github.com/debiki/talkyard/blob/main/images/backup/Dockerfile
    profiles: [backup] # prevents auto-start on 'up'
    restart: no
    # If under heavy load, run the backup script at 25% priority. (Default is 1024 shares.)
    cpu_shares: 256
    # Don't let the backup container use more than 60% CPU (even if the system is idle),
    # otherwise on a small VM the kernel might panic [100_kernel_panic].
    cpu_quota:   60000
    cpu_period: 100000
    secrets:
      # Will appear at /run/secrets/postgres_password. [backup_pg_client_secret]
      - postgres_password
      #- backup_password
    volumes:
      # Here we save the backups.
      - /var/opt/backups/talkyard/v1:/var/opt/backups/talkyard/v1
      # So can backup uploaded files and Redis.
      - pub-files:/var/talkyard/v1/pub-files:ro
      - priv-files:/var/talkyard/v1/priv-files:ro
      - redis-data:/var/talkyard/v1/redis-data:ro
      # So can backup config files.
      - .:/opt/talkyard-v1:ro
    logging: *default_logging
    depends_on:
      # So can backup database.
      - rdb
    networks:
      be_int_net:
    security_opt:
      - no-new-privileges=true
    cap_drop:
      - ALL
    cap_add:
      # So 'root' can access Redis' dump.rdb file, which is owned by user 'redis' 999.
      - CAP_DAC_READ_SEARCH

# vim: et ts=2 sw=2
