# Dockerfiles for the Docker images are in another Git repo:
# https://github.com/debiki/talkyard, at: images/(image-name)/Dockerfile
#
# There's an image build script: https://github.com/debiki/talkyard/blob/main/Makefile,
# the `prod-images` and `tag-and-push-latest-images` targets.

# Docker Compose file spec:
# https://github.com/compose-spec/compose-spec/blob/main/spec.md


# You can create using ./scripts/create-volumes.sh.
volumes:
  #talkyard-v1-backups: { external: true }
  talkyard-v1-web-acme: { external: true }
  talkyard-v1-pub-files: { external: true }
  talkyard-v1-priv-files: { external: true }
  talkyard-v1-pg-data: { external: true }
  talkyard-v1-cache-data: { external: true }
  talkyard-v1-es-data: { external: true }
  talkyard-v1-es-logs: { external: true }

networks:
  # This netw name get prefixed with COMPOSE_PROJECT_NAME  = 'talkyard_' by Docker, from .env.
  internal_net:
    driver: bridge
    ipam:
      config:
        - subnet: ${INTERNAL_NET_SUBNET}

# See: https://github.com/compose-spec/compose-spec/blob/main/spec.md#logging
x-logging: &default_logging
  driver: local

services:
  web:
    image: ${DOCKER_REPOSITORY}/talkyard-web:${VERSION_TAG}
    # dockerfile: https://github.com/debiki/talkyard/blob/main/images/web/Dockerfile
    restart: always
    volumes:
      # The LetsEncrypt ACME account key gets generated by run-envsubst-gen-keys.sh.
      # Once done, you could make this dir read-only: append ':ro' to the next line.
      - talkyard-v1-web-acme:/etc/nginx/acme
      # ./conf/sites-enabled-manual/:/etc/nginx/sites-enabled-manual/:ro
      - ./conf/web/sites-enabled:/etc/nginx/sites-enabled:ro
      # ./data/sites-enabled-auto-gen/:/etc/nginx/sites-enabled-auto-gen/:ro
      #----
      # Not using certbot any more, except for DNS but then we'd edit a DNS entry. Clean up!
      #- ./data/certbot/:/etc/certbot/:ro
      #- ./data/certbot-challenges/.well-known/:/opt/nginx/html/.well-known/:ro
      #----
      # Don't, however, mount talkyard-v1-priv-files here.
      - talkyard-v1-pub-files:/opt/talkyard/pub-files:ro
    ports:
      - '80:80'
      - '443:443'
    networks:
      internal_net:
        ipv4_address: ${INTERNAL_NET_WEB_IP}
    depends_on:
      - app
    logging: *default_logging
    environment:
      TY_NGX_ERROR_LOG_LEVEL: 'info'  # or 'notice' or 'debug'
      # TY_NGX_ACCESS_LOG_CONFIG: 'tyalogfmt'
      ## Max uploaded file size, e.g. uploaded images or backups to restore:
      # TY_NGX_LIMIT_REQ_BODY_SIZE: '25m'
      ## To let any CDN of yours bypass Ty's Nginx rate limits:
      # X_PULL_KEY: '...'
      # CDN_PULL_KEY: '...'

    # When cap_drop is ALL, it gets processed before cap_add, see:
    # https://stackoverflow.com/a/63219871
    # and:
    # https://github.com/moby/moby/blob/1c39b1c44c973f18f39bd684c6aba57bb96510fe/oci/caps/utils.go#L120
    cap_drop:
      - ALL
    cap_add:
      # Without CHOWN:
      # nginx: [emerg] chown("/opt/nginx/proxy-cache", 100) failed (1: Operation not permitted)
      - CHOWN
      # To bypass file read, write, and execute permission checks:
      # (DAC means "discretionary access control", and DAC_OVERRIDE)
      # Without DAC_OVERRIDE:
      # nginx: [emerg] mkdir() "/var/cache/nginx/client_temp" failed (13: Permission denied)
      - DAC_OVERRIDE
      # To change the group and user id of a process: (so Nginx won't need to run as root)
      - SETGID
      - SETUID
      # To bind to lower ports. Maybe listen on 8080 instead, and map port 80:8080?
      - NET_BIND_SERVICE

  app:
    image: ${DOCKER_REPOSITORY}/talkyard-app:${VERSION_TAG}
    # dockerfile: https://github.com/debiki/talkyard/blob/main/images/app/Dockerfile.prod
    restart: always
    stdin_open: true  # otherwise Play Framework exits
    volumes:
      - ./conf/app/play-framework.conf:/opt/talkyard/app/conf/app-prod-override.conf:ro  # see [4WDKPU2] in debiki/talkyard
      - talkyard-v1-pub-files:/opt/talkyard/pub-files
      - talkyard-v1-priv-files:/opt/talkyard/priv-files
      # So backups can be downloaded via the admin web interface. But read-only,
      # so evil bugs cannot destroy all backups.
      # - /var/opt/backups/talkyard/v1/:/var/opt/backups/talkyard/v1/:ro
    networks:
      internal_net:
        ipv4_address: ${INTERNAL_NET_APP_IP}
    depends_on:
      # Start also if unhealthy. Then, can show admin friendly troubleshooting tips.
      - cache
      - rdb
      - search
    logging: *default_logging
    environment:
      - PLAY_SECRET_KEY
      - TALKYARD_SECURE
      - POSTGRES_PASSWORD
      - TALKYARD_HOSTNAME
      - BECOME_OWNER_EMAIL_ADDRESS
    cap_drop:
      - ALL
    cap_add:  # is this enough?
      - SETGID
      - SETUID

  cache:
    image: ${DOCKER_REPOSITORY}/talkyard-cache:${VERSION_TAG}
    # dockerfile: https://github.com/debiki/talkyard/blob/main/images/cache/Dockerfile
    restart: always
    volumes:
      - talkyard-v1-cache-data:/data
    networks:
      internal_net:
        ipv4_address: ${INTERNAL_NET_CACHE_IP}
    logging: *default_logging
    sysctls:
      net.core.somaxconn: 511
    healthcheck:  # move to image?
      test: redis-cli ping | grep PONG
      start_period: 60s
      start_interval: 1s
      interval: 20s
      timeout: 5s
      retries: 5
    cap_drop:
      - ALL
    cap_add: # [enough_caps]? See: https://github.com/docker-library/postgres/issues/649
      - CHOWN  # [redis_cap_chown]
      - SETGID
      - SETUID
      - KILL # ?

  rdb:
    image: ${DOCKER_REPOSITORY}/talkyard-rdb:${VERSION_TAG}
    # dockerfile: https://github.com/debiki/talkyard/blob/main/images/rdb/Dockerfile
    restart: always
    volumes:
      - talkyard-v1-pg-data:/var/lib/postgresql/data
      - ./conf/rdb:/var/lib/postgresql/conf
    networks:
      internal_net:
        ipv4_address: ${INTERNAL_NET_RDB_IP}
    logging: *default_logging
    environment:
      POSTGRES_PASSWORD: '$POSTGRES_PASSWORD'
    cap_drop:
      - ALL
    cap_add: # [enough_caps]? See: https://github.com/docker-library/postgres/issues/649
      - CHOWN
      - DAC_READ_SEARCH
      - FOWNER
      - SETGID
      - SETUID
      - SYS_NICE
    healthcheck:  # move into image?
      test: pg_isready -U postgres
      start_period: 60s
      start_interval: 1s
      interval: 20s
      timeout: 5s
      retries: 5

  search:
    image: ${DOCKER_REPOSITORY}/talkyard-search:${VERSION_TAG}
    # dockerfile: https://github.com/debiki/talkyard/blob/main/images/search/Dockerfile
    restart: always
    volumes:
      - talkyard-v1-es-data:/usr/share/elasticsearch/data
      # Deprecation logs aren't written to stdout, but to files in this dir,
      # auto rotated, max 5G in total.
      # See: https://www.elastic.co/docs/deploy-manage/monitor/logging-configuration/elasticsearch-deprecation-logs
      - talkyard-v1-es-logs:/usr/share/elasticsearch/logs

    networks:
      internal_net:
        ipv4_address: ${INTERNAL_NET_SEARCH_IP}
    logging: *default_logging
    environment:
      bootstrap.memory_lock: 'true'
      ES_JAVA_OPTS: '-Xms512m -Xmx512m'
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_drop:
      - ALL
    cap_add:  # [enough_caps]?
      # SYS_CHROOT? See  https://github.com/nasa-jpl/ASSESS/blob/master/docker-compose.yml
      - SETGID
      - SETUID
      # KILL?

# vim: et ts=2 sw=2
