# Talkyard kernel parameters
#
# (Added by Talkyard's prepare-os.sh installation script.)

# Turn off swap, default = 60.
vm.swappiness=0

# Up the max backlog queue size (num connections per port), default = 128.
# Sync with conf/web/sites-enabled/talkyard-servers.conf.
net.core.somaxconn=8192

# More virtual memory, for ElasticSearch.
# See: https://www.elastic.co/docs/deploy-manage/deploy/self-managed/vm-max-map-count
# Seems 1048576 is the default nowadays (Debian 13), but let's anyway:
vm.max_map_count=1048576

